---
- name: Set config file parameters
  template:
    src: application.conf.j2
    dest: "{{ kafka_manager_base_dir }}/kafka-manager-{{ kafka_manager_version }}/conf/application.conf"

- name: Ensure kafka-manager is running
  service: name=kafka-manager state=started enabled=yes
